C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\Django-Middleware-0x03\messaging_app\settings.py changed, reloading.
2025-01-17 17:47:56 - User: Anonymous - Path: /api/conversations/
Internal Server Error: /api/conversations/
Traceback (most recent call last):
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2761, in to_python
    return uuid.UUID(**{input_form: value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\uuid.py", line 175, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
          ^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\Django-Middleware-0x03\chats\views.py", line 15, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2745, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbbag\repos\Development Operations\Portfolio\alx-backend-python\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2763, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
